{% set version = "0.2.4" %}

package:
  name: peprs
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/peprs/peprs-{{ version }}.tar.gz
  sha256: 4eca72893301cf7b0967c2c5ed1707029bfcbb9d6613c4146028ecb61842224a

build:
  entry_points:
    - peprs = peprs:_cli_main
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.9,<2.0
    - pip
    - polars
    - pyarrow
  run:
    - python

test:
  imports:
    - peprs
  commands:
    - pip check
    - peprs --help
  requires:
    - pip
    - python

about:
  home: https://github.com/khoroshevskyi/peprs/
  summary: Rust-powered PEP sample metadata toolkit for Python
  license: MIT
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - khoroshevskyi