{% set version = "0.2.1" %}

package:
  name: peprs
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/peprs/peprs-{{ version }}.tar.gz
  sha256: 44c3beef6fb268036f257e01cd31dd1a702fc65e484c49942f6243b186733301

build:
  entry_points:
    - peprs = peprs:_cli_main
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.9,<2.0
    - pip
  run:
    - python

test:
  imports:
    - peprs
  commands:
    - pip check
    - peprs --help
  requires:
    - pip
    - python

about:
  home: https://github.com/khoroshevskyi/peprs/
  summary: Rust-powered PEP sample metadata toolkit for Python
  license: MIT
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - khoroshevskyi
